apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: web-app
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # Service Port
      targetPort: 80    # Port the container is listening on
      nodePort: 30080
  type: NodePort
